"""add contract generation v1 tables

Revision ID: a93beeaddf82
Revises: 011_market_prices_ptf_admin
Create Date: 2026-08-03 16:42:07.529049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93beeaddf82'
down_revision: Union[str, None] = '011_market_prices_ptf_admin'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_legal_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('tax_number', sa.String(length=20), nullable=False),
    sa.Column('tax_office', sa.String(length=255), nullable=False),
    sa.Column('mersis_number', sa.String(length=32), nullable=True),
    sa.Column('trade_registry_number', sa.String(length=64), nullable=True),
    sa.Column('registered_address', sa.Text(), nullable=False),
    sa.Column('facility_address', sa.Text(), nullable=True),
    sa.Column('notification_address', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_legal_profiles_customer_id'), 'customer_legal_profiles', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_legal_profiles_id'), 'customer_legal_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_customer_legal_profiles_tenant_id'), 'customer_legal_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_customer_legal_profiles_verification_status'), 'customer_legal_profiles', ['verification_status'], unique=False)
    op.create_table('uploaded_reference_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_ref', sa.String(length=500), nullable=False),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'customer_id', 'sha256', name='uq_reference_doc_dedup')
    )
    op.create_index(op.f('ix_uploaded_reference_documents_customer_id'), 'uploaded_reference_documents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_uploaded_reference_documents_document_type'), 'uploaded_reference_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_uploaded_reference_documents_id'), 'uploaded_reference_documents', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_reference_documents_processing_status'), 'uploaded_reference_documents', ['processing_status'], unique=False)
    op.create_index(op.f('ix_uploaded_reference_documents_sha256'), 'uploaded_reference_documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_uploaded_reference_documents_tenant_id'), 'uploaded_reference_documents', ['tenant_id'], unique=False)
    op.create_table('customer_authorized_representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('legal_profile_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('national_id', sa.String(length=11), nullable=False),
    sa.Column('authority_type', sa.String(length=50), nullable=True),
    sa.Column('authority_scope', sa.String(length=255), nullable=True),
    sa.Column('authority_start_date', sa.DateTime(), nullable=True),
    sa.Column('authority_end_date', sa.DateTime(), nullable=True),
    sa.Column('is_indefinite', sa.Boolean(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['legal_profile_id'], ['customer_legal_profiles.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['uploaded_reference_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_authorized_representatives_customer_id'), 'customer_authorized_representatives', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_authorized_representatives_id'), 'customer_authorized_representatives', ['id'], unique=False)
    op.create_index(op.f('ix_customer_authorized_representatives_legal_profile_id'), 'customer_authorized_representatives', ['legal_profile_id'], unique=False)
    op.create_index(op.f('ix_customer_authorized_representatives_tenant_id'), 'customer_authorized_representatives', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_customer_authorized_representatives_verification_status'), 'customer_authorized_representatives', ['verification_status'], unique=False)
    op.create_table('document_extraction_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('extractor_type', sa.String(length=50), nullable=False),
    sa.Column('extractor_version', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_response_ref', sa.String(length=500), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_reference_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_extraction_runs_document_id'), 'document_extraction_runs', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_extraction_runs_id'), 'document_extraction_runs', ['id'], unique=False)
    op.create_index(op.f('ix_document_extraction_runs_status'), 'document_extraction_runs', ['status'], unique=False)
    op.create_index(op.f('ix_document_extraction_runs_tenant_id'), 'document_extraction_runs', ['tenant_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('legal_profile_id', sa.Integer(), nullable=True),
    sa.Column('authorized_representative_id', sa.Integer(), nullable=True),
    sa.Column('contract_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('template_version', sa.String(length=20), nullable=True),
    sa.Column('extraction_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('contract_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('pdf_storage_ref', sa.String(length=500), nullable=True),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['authorized_representative_id'], ['customer_authorized_representatives.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['legal_profile_id'], ['customer_legal_profiles.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_number'), 'contracts', ['contract_number'], unique=True)
    op.create_index(op.f('ix_contracts_customer_id'), 'contracts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_offer_id'), 'contracts', ['offer_id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.create_table('document_field_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('extraction_run_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('conflict_status', sa.String(length=20), nullable=False),
    sa.Column('user_decision', sa.String(length=20), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['uploaded_reference_documents.id'], ),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['document_extraction_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_field_candidates_conflict_status'), 'document_field_candidates', ['conflict_status'], unique=False)
    op.create_index(op.f('ix_document_field_candidates_document_id'), 'document_field_candidates', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_field_candidates_extraction_run_id'), 'document_field_candidates', ['extraction_run_id'], unique=False)
    op.create_index(op.f('ix_document_field_candidates_field_name'), 'document_field_candidates', ['field_name'], unique=False)
    op.create_index(op.f('ix_document_field_candidates_id'), 'document_field_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_document_field_candidates_tenant_id'), 'document_field_candidates', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_document_field_candidates_validation_status'), 'document_field_candidates', ['validation_status'], unique=False)
    # ### end Alembic commands ###
    # NOT: autogenerate burada audit_logs/customers/invoices/jobs/
    # market_reference_prices/offers/webhook_* tablolarında bu PATCH'ten
    # bağımsız, önceden var olan model↔migration sapmaları da yakalamıştı
    # (başka branch'lerin ORM modeline ekleyip migration yazmadığı alanlar).
    # Kapsam dışı olduğu için kasıtlı olarak buradan çıkarıldı — yalnız
    # contract-generation'ın 6 yeni tablosu bırakıldı.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_field_candidates_validation_status'), table_name='document_field_candidates')
    op.drop_index(op.f('ix_document_field_candidates_tenant_id'), table_name='document_field_candidates')
    op.drop_index(op.f('ix_document_field_candidates_id'), table_name='document_field_candidates')
    op.drop_index(op.f('ix_document_field_candidates_field_name'), table_name='document_field_candidates')
    op.drop_index(op.f('ix_document_field_candidates_extraction_run_id'), table_name='document_field_candidates')
    op.drop_index(op.f('ix_document_field_candidates_document_id'), table_name='document_field_candidates')
    op.drop_index(op.f('ix_document_field_candidates_conflict_status'), table_name='document_field_candidates')
    op.drop_table('document_field_candidates')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_offer_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_customer_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_number'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_document_extraction_runs_tenant_id'), table_name='document_extraction_runs')
    op.drop_index(op.f('ix_document_extraction_runs_status'), table_name='document_extraction_runs')
    op.drop_index(op.f('ix_document_extraction_runs_id'), table_name='document_extraction_runs')
    op.drop_index(op.f('ix_document_extraction_runs_document_id'), table_name='document_extraction_runs')
    op.drop_table('document_extraction_runs')
    op.drop_index(op.f('ix_customer_authorized_representatives_verification_status'), table_name='customer_authorized_representatives')
    op.drop_index(op.f('ix_customer_authorized_representatives_tenant_id'), table_name='customer_authorized_representatives')
    op.drop_index(op.f('ix_customer_authorized_representatives_legal_profile_id'), table_name='customer_authorized_representatives')
    op.drop_index(op.f('ix_customer_authorized_representatives_id'), table_name='customer_authorized_representatives')
    op.drop_index(op.f('ix_customer_authorized_representatives_customer_id'), table_name='customer_authorized_representatives')
    op.drop_table('customer_authorized_representatives')
    op.drop_index(op.f('ix_uploaded_reference_documents_tenant_id'), table_name='uploaded_reference_documents')
    op.drop_index(op.f('ix_uploaded_reference_documents_sha256'), table_name='uploaded_reference_documents')
    op.drop_index(op.f('ix_uploaded_reference_documents_processing_status'), table_name='uploaded_reference_documents')
    op.drop_index(op.f('ix_uploaded_reference_documents_id'), table_name='uploaded_reference_documents')
    op.drop_index(op.f('ix_uploaded_reference_documents_document_type'), table_name='uploaded_reference_documents')
    op.drop_index(op.f('ix_uploaded_reference_documents_customer_id'), table_name='uploaded_reference_documents')
    op.drop_table('uploaded_reference_documents')
    op.drop_index(op.f('ix_customer_legal_profiles_verification_status'), table_name='customer_legal_profiles')
    op.drop_index(op.f('ix_customer_legal_profiles_tenant_id'), table_name='customer_legal_profiles')
    op.drop_index(op.f('ix_customer_legal_profiles_id'), table_name='customer_legal_profiles')
    op.drop_index(op.f('ix_customer_legal_profiles_customer_id'), table_name='customer_legal_profiles')
    op.drop_table('customer_legal_profiles')
    # ### end Alembic commands ###
